version: "3.9"

services:
  app:
    build: ./app/
    depends_on:
      - db
      - flyway
    links:
      - "db:db" 
    # volumes:
      # - C:\Users\Admin\Desktop\to git\lab1\app:/app
  
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/znodata -schemas=public -user=postgres -password=password -connectRetries=60 migrate
    volumes:
      - ./app/flyway/sql:/flyway/sql
    depends_on:
      - db
  
  db:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: znodata
    ports:
      - 5432:5432
    volumes:
      - pgdata:/app/var/lib/postgresql/data/


volumes:
  pgdata:
